//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab19F.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrder
    {
        public int POid { get; set; }
        public int Pid { get; set; }
        public int Oid { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
